import SwiftUI
import SuspensionKit
#if canImport(AppKit)
import AppKit
#elseif canImport(UIKit)
import UIKit
#endif

/// Light, print-friendly version of the results used for Share → image and Print.
struct ReportView: View {
    let model: SuspensionModel
    let rec: Recommendation
    let riderSummary: String
    let disclaimer: String

    var body: some View {
        VStack(alignment: .leading, spacing: 16) {
            HStack(spacing: 14) {
                BrandBadge(brand: model.brand, size: 56)
                VStack(alignment: .leading, spacing: 3) {
                    Text("\(model.brand) \(model.name)").font(.system(size: 24, weight: .heavy))
                    Text("\(model.kind.rawValue.capitalized) · \(model.spring.rawValue.capitalized) spring · \(model.damper) damper")
                        .font(.subheadline).foregroundStyle(.secondary)
                    Text(riderSummary).font(.subheadline.weight(.semibold)).foregroundStyle(Theme.goDeep)
                }
            }

            HStack {
                VStack(alignment: .leading, spacing: 2) {
                    Text(rec.headlineLabel.uppercased()).font(.caption.bold()).opacity(0.8)
                    Text("\(rec.headlineValue) \(rec.headlineUnit)").font(.system(size: 40, weight: .heavy, design: .rounded))
                }
                Spacer()
                if let sag = rec.value("Sag") {
                    VStack(alignment: .trailing, spacing: 2) {
                        Text("TARGET SAG").font(.caption.bold()).opacity(0.8)
                        Text(sag.replacingOccurrences(of: "  ·  ", with: " / ")).font(.title2.bold())
                    }
                }
            }
            .foregroundStyle(.white)
            .padding(20)
            .background(LinearGradient(colors: [Theme.goBright, Theme.goDeep], startPoint: .topLeading, endPoint: .bottomTrailing),
                        in: RoundedRectangle(cornerRadius: 14))

            VStack(spacing: 0) {
                ForEach(Array(rec.settings.dropFirst().filter { $0.label != "Sag" }.enumerated()), id: \.offset) { i, s in
                    HStack(alignment: .firstTextBaseline) {
                        Label {
                            Text(s.label)
                        } icon: {
                            Image(systemName: Theme.style(for: s.label).icon)
                                .foregroundStyle(Theme.style(for: s.label).color)
                        }
                        .font(.callout.weight(.semibold))
                            .frame(width: 230, alignment: .leading)
                        VStack(alignment: .leading, spacing: 2) {
                            Text(s.value).font(.callout.bold())
                            Text(s.detail).font(.caption).foregroundStyle(.secondary)
                        }
                        Spacer()
                    }
                    .padding(.vertical, 9).padding(.horizontal, 12)
                    .background(i.isMultiple(of: 2) ? Color.black.opacity(0.04) : .clear)
                }
            }
            .clipShape(RoundedRectangle(cornerRadius: 10))

            ForEach(rec.warnings, id: \.self) { w in
                Label(w, systemImage: "exclamationmark.triangle.fill").font(.callout).foregroundStyle(.orange)
            }
            VStack(alignment: .leading, spacing: 4) {
                Text("SETUP NOTES").font(.caption.bold()).foregroundStyle(Theme.goDeep)
                ForEach(rec.tips, id: \.self) { Text("• \($0)").font(.callout) }
            }
            Text(disclaimer).font(.caption).foregroundStyle(.secondary)
            Text("Generated by Suspension Tuner").font(.caption2).foregroundStyle(.secondary)
        }
        .foregroundStyle(.black)
        .padding(32)
        .frame(width: 640, alignment: .leading)
        .background(.white)
        .environment(\.colorScheme, .light)
    }
}

@MainActor
enum Exporter {
    static let scale: CGFloat = 2

    static func cgImage<V: View>(of view: V) -> CGImage? {
        let renderer = ImageRenderer(content: view)
        renderer.scale = scale
        return renderer.cgImage
    }

    static func image<V: View>(of view: V) -> Image? {
        cgImage(of: view).map { Image(decorative: $0, scale: scale) }
    }

    static func printReport<V: View>(_ view: V, title: String) {
        guard let cg = cgImage(of: view) else { return }
        #if canImport(AppKit)
        let size = NSSize(width: CGFloat(cg.width) / scale, height: CGFloat(cg.height) / scale)
        let imageView = NSImageView(frame: NSRect(origin: .zero, size: size))
        imageView.image = NSImage(cgImage: cg, size: size)
        imageView.imageScaling = .scaleProportionallyUpOrDown
        let info = (NSPrintInfo.shared.copy() as? NSPrintInfo) ?? NSPrintInfo()
        info.horizontalPagination = .fit
        info.verticalPagination = .fit
        info.isHorizontallyCentered = true
        info.isVerticallyCentered = false
        let op = NSPrintOperation(view: imageView, printInfo: info)
        op.jobTitle = title
        op.run()
        #elseif canImport(UIKit)
        let info = UIPrintInfo(dictionary: nil)
        info.outputType = .general
        info.jobName = title
        let controller = UIPrintInteractionController.shared
        controller.printInfo = info
        controller.printingItem = UIImage(cgImage: cg)
        controller.present(animated: true)
        #endif
    }
}
